### ISSUE TITLE
Unable to change CHARGE_MODE. Just stopped working this week. Related to beta-programme? Now GA!

### ISSUE THREAD

**Issue by GPDixon** [gndean/home-assistant-hypervolt-charger#40] opened 2024-01-26 10:07 UTC
My integration has been working for months but suddenly (this week) I've noticed that the charge_mode (Boost, Eco, Super Eco) has stopped working. I can change it in HA but that change is not changed in the Hypervolt app (and vica versa). I don't think I get any error in the log files.
I have a suspicion it's related to the fact that I signed up to the Hypervolt beta test program. I believe there is a change they are/have implemented to change the way that the charge mode works? I believe they are enabling each schedule slot to specify its own charge mode and perhaps this changes/impacts the integration?

**Comment by GPDixon** [comment] 2024-02-10 14:24
This beta change has now gone GA (General Availability) and so should be rolled out to everyone soon (next few days). Can people confirm they don't now have the same problem? Changing the charge mode no longer works?

**Comment by ptashek** [comment] 2024-03-12 01:24
I can confirm that changing the charge mode from the integration no longer works.
HV 3.0 + FW 2627.0

**Comment by GPDixon** [comment] 2024-03-12 09:02
same combination as me.

**Comment by gndean** [comment] 2024-03-12 09:29
OK, thanks for confirming.

It's still working for me on a HV 2.0 unit so I guess it's another v2/v3 difference.

I'll see if I can work out some way of diagnosing this but it's not going to be easy as I can't see the issue here. I'll let you know if you can help with this.

**Comment by GPDixon** [comment] 2024-03-12 09:45
I 'think' the issue has been the recent change where they made the charge mode an attribute of each schedule... i.e. you can define a different charge mode for each of your schedules... whereas before it used to be just at the 'global' level. I don't even use schedules! I control everything through HA. Thanks for looking in to it. It's made my HA control a it clunky to work around it. I used to simply change the mode from SOLAR to BOOST when I wanted to force a charge. It would be nice to go back to that or I won't be able to benefit form excess SOLAR... should we ever have any this summer!

**Comment by GPDixon** [comment] 2024-03-12 09:46
Happy to help. Indeed I'd be interested to find out how you go about working through this. I don't think Hypervolt provide any documentation do they? I assume you are somehow sniffing out the API calls? I'd very much like to contribute.

**Comment by ptashek** [comment] 2024-03-19 13:51
Also happy to help with any investigation / debugging / testing, if that helps making this integration even better than it already is :)

**Comment by gndean** [comment] 2024-03-22 19:38
I now have access to a Hypervolt 3.0 and can repeat this issue. So I'll look into fixing this as soon as I can.

**Comment by GPDixon** [comment] 2024-03-23 09:04
Fantastic. Have missed this feature.

**Comment by gndean** [comment] 2024-04-01 21:18
I have created a beta release with a fix for this, the Charge Mode and also adding in the V3.0 scheduling features:
https://github.com/gndean/home-assistant-hypervolt-charger/releases/tag/v2.0.1-beta

I've also significantly changed the internal login process as well as fair few other changes due to the differences between HV v2.0 and v3.0 devices, so there's a good chance some stuff is broken. But please give it a try if you have chance.

**Comment by GPDixon** [comment] 2024-04-02 09:28
Have tried this morning. Not sure I could see any difference. I've attached by home assistant log file after setting the BETA integration to "enable debugging". I can see an error in Async_setup_entry exception but not much else. I went through a process of (1) set lock state OFF, (2) set charge mode to ECO, (3) set lock state ON changing, (4) set charge mode to BOOST. The log seems to think everything worked but the formal Hypervolt app didn't change at all. Conversely, when I changed in the app, the integration reflected the change almost immediately. I blanked out **REMOVED** some of the identifiers.
[hypervolt-beta.log](https://github.com/gndean/home-assistant-hypervolt-charger/files/14834457/hypervolt-beta.log)

**Comment by gndean** [comment] 2024-04-02 10:26
I don't think the HV mobile app always shows the updated status. Do you have two devices with the app installed? If so, you could try changing in the settings in one and seeing if they're reflected in the other. In my experience, it's not always the case and there's nothing the HA integration can do about that.

**Comment by GPDixon** [comment] 2024-04-02 11:59
Tried with 2 phones as suggested. Changes to the lock status are immediately reflected in both phones. Changes to the charge mode (e.g. Boost, Eco, Super Eco) are not! However, if you drag down on the schematic/diagram then there is the usual circular "updating" icon and the charge mode is then refreshed correctly. I'll try with phone + HA again to check I was doing it OK but I'm pretty certain that changes made via HA were not being reflected in the phone App (famous last words!).

**Comment by GPDixon** [comment] 2024-04-03 09:04
OK. Have tried some more. I think I agree with you. The behaviour of the mobile app seems a little varied... it's refresh process evens differs depending on whether the car is plugged in or not. However, after more testing I'm still not able to get the outcome I was looking for. Have attached a debug log file. To turn the charger on I have this automation action:

     - service: homeassistant.turn_off
       entity_id: switch.hypervolt_lock_state
     - service: select.select_option
       target:
         entity_id: select.hypervolt_activation_mode
       data:
         option: "Plug and Charge"
     - service: select.select_option
       target:
         entity_id: select.hypervolt_charge_mode
       data:
         option: "Boost"
     - service: homeassistant.turn_on (I think this step is entirely redundant is it even a switch??)
       entity_id: switch.hypervolt_charging

In the debug log you can see this working

To turn off the action is:

   action:
     - service: homeassistant.turn_off
       entity_id: switch.hypervolt_lock_state
     - service: select.select_option
       target:
         entity_id: select.hypervolt_activation_mode
       data:
         option: "Plug and Charge"
     - service: select.select_option
       target:
         entity_id: select.hypervolt_charge_mode
       data:
         option: "Super Eco"
     - service: homeassistant.turn_off
       entity_id: switch.hypervolt_charging
     - service: homeassistant.turn_on
       entity_id: switch.hypervolt_lock_state

This sort of works....except you can see in the DEBUG log file that 'something' is immediately turning the charge_mode back from "Super Eco" to "Boost". What could be doing this? 

There are also several warnings in the DEBUG log...
On_sync_websocket_message_callback error $'NoneType' object has no attribute 'age_ms'
[2024-04-03 hypervolt-beta.log](https://github.com/gndean/home-assistant-hypervolt-charger/files/14849691/2024-04-03.hypervolt-beta.log)

**Comment by gndean** [comment] 2024-04-13 12:09
@GPDixon I've been trying to understand and repeat this issue where the charge mode gets set back to Boost.
I can sometimes repeat it with your "turn off" automation, and sometimes not. I suspect it's some kind of race condition (stuff happening in arbitrary order) when requesting all those actions to happen in immediate succession and the HV servers trying to coordinate the actions.

I couldn't seem to repeat the issue when adding delays between the steps e.g.
```action:
  - service: homeassistant.turn_off
    entity_id: switch.hypervolt_lock_state
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: select.select_option
    target:
      entity_id: select.hypervolt_activation_mode
    data:
      option: Plug and Charge
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: select.select_option
    target:
      entity_id: select.hypervolt_charge_mode
    data:
      option: Super Eco
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: homeassistant.turn_off
    entity_id: switch.hypervolt_charging
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: homeassistant.turn_on
    entity_id: switch.hypervolt_lock_state
```
I did this to try and diagnose the issue but maybe this could be a workaround. Not sure if all the steps required a delay.

I'd like a better solution than this, but I'd be interested to know if this works around the issue for you?

It's still hard to debug because the HV app still doesn't always show the most up-to-date status, so trying to see what the real state is, is sometimes guesswork!

**Comment by GPDixon** [comment] 2024-04-13 13:21
Hi, funnily enough I was trying exactly the same yesterday and also tried using a delay. It seems to work! I also use belt and braces and set the mode 3 times in a row!! Not very elegant but the outcome is the same. Like you said, it only seems to be an issue on the turn_off automation. I wonder if it might also be something to do with boost being a default option as well. Thank you ever so much for following up on it. I find Hypervolt's combination of lock/unlock and the charge switch not very intuitive in their app. It would be good to get a proper explanation from them. I'm sure it could be much simpler!

**Comment by gndean** [comment] 2024-04-13 13:37
Forcing the charging on/off via the charging switch is something the HV app's not supported for a while. When I first created the integration, it had this feature but not now. It might be best not to rely on this now. I might deprecate this switch with tine HA integration in the future.
For my automations, when I want to force charging to stop, I instead switch the Activation Mode to Schedule. Maybe that's another option?

**Comment by GPDixon** [comment] 2024-04-13 16:51
The charge switch does now do something! With the latest app there is a pause function. If you turn the charge switch off when it is charging then it seems to involve the pause status. Please don't deprecate yet!!!

**Comment by GPDixon** [comment] 2024-04-13 16:52
When I get home tomorrow I'll take some screenshots... Although I don't think GitHub will let me upload?

**Comment by GPDixon** [comment] 2024-04-13 17:04
The hypervolt app now clearly indicates when the car is plugged in or not. Any chance you can add that as a sensor please? I could then use it to request info from the car on how much juice it needs.

**Comment by gndean** [comment] 2024-04-13 19:22
> The hypervolt app now clearly indicates when the car is plugged in or not. Any chance you can add that as a sensor please? I could then use it to request info from the car on how much juice it needs.

Yes, this is covered by https://github.com/gndean/home-assistant-hypervolt-charger/issues/43

Are you happy for this issue to be closed now? I think the fundamental issue is resolved, as much as it can be right now.

**Comment by GPDixon** [comment] 2024-04-14 07:45
Yes. I think you are right. Many thanks

Yahoo Mail: Search, organise, conquer 
 
  On Sat, 13 Apr 2024 at 20:22, ***@***.***> wrote:   



The hypervolt app now clearly indicates when the car is plugged in or not. Any chance you can add that as a sensor please? I could then use it to request info from the car on how much juice it needs.


Yes, this is covered by #43

Are you happy for this issue to be closed now? I think the fundamental issue is resolved, as much as it can be right now.

**Closed** 2024-04-14 07:47 UTC
Labels: bug
